version: "3.9"
services:
#    web:
#        build: .
#        ports:
#            - "8000:80"
#        depends_on:
#            - db
    db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        container_name: MEHUL-MSSQL-SERVER
        hostname: MEHUL-MSSQL-SERVER
        env_file:
          - ENV/SQL_SERVER.env
        ports:
          - "1433:1433"
        volumes:
          - "D:/CloudSync/GoogleDrive/school/NJIT Masters/Spring 2021/CS631/Project 3/docker-db/data:/var/opt/mssql/data"
          - "D:/CloudSync/GoogleDrive/school/NJIT Masters/Spring 2021/CS631/Project 3/docker-db/log:/var/opt/mssql/log"
          - "D:/CloudSync/GoogleDrive/school/NJIT Masters/Spring 2021/CS631/Project 3/docker-db/secrets:/var/opt/mssql/secrets"
